### ISSUE TITLE
Add automatic updater

### ISSUE THREAD

**Issue by RiedleroD** [RiedleroD/Rtris#15]
self-upgrading of course.
Oh and it shouldn't update if the .git folder is there.
Oh and there should be a command line argument (-U, --update) that tells the game to only update itself.

**Comment by mfederczuk** [comment]
The script could download the newest version of the file from <https://raw.githubusercontent.com/RiedleroD/Rtris/master/rtris.py> to the `/tmp` directory, create a sha-1 checksum of it and of itself and them compare the two checksum.  
If they are different then you could replace the existing file with the downloaded one

**Comment by RiedleroD** [comment]
Or we could just add a variable "version" to the config file and only download when it differs from the online one.

**Comment by mfederczuk** [comment]
Yeah that would be better wouldn't it? I dunno why I though so complicated there.

Only problem is, where would we store the online version number.  
We could either create a JSON file for it, or the script could somehow check the Git tags of the remote repository

**Comment by RiedleroD** [comment]
That's also easy. Just let the users decide if they want dev or release mode and then just either fetch the latest commit or Release. (oh maybe prereleases should get seperated too)

**Comment by mfederczuk** [comment]
The option could look something like that:

```
-u, --update[=dev]  update the script automatically. By default, fetch the latest stable release, add the "dev" argument to fetch the latest, pre-release changes
```

**Comment by RiedleroD** [comment]
since update is most of the time a capital U, we should do that too. Also, I will add these functions to the UI too.

**Comment by mfederczuk** [comment]
No we only need to figure out how we would get tag name of the latest release.  
After that we can download the file from `https://raw.githubusercontent.com/RiedleroD/Rtris/<tag-name>/rtris.py` and replace it with the old one.

If we don't add a file in the repository that always holds the tag name of the latest release, we would need to somehow clone the repository locally and do some Git magic

**Comment by RiedleroD** [comment]
`https://api.github.com/repos/RiedleroD/Rtris/commits/master` should provide information about all commits, and `https://api.github.com/repos/RiedleroD/Rtris/releases` should contain information about all releases. Then we just have to extract the latest one.
We don't need an extra file to hold the tag name, I already made one (~/.rtrisconf) which is basically the config file.

**Comment by mfederczuk** [comment]
Well then we're all set, ask if you need any help implementing it

**Comment by RiedleroD** [comment]
I'm done doing the basic stuff. There's still some more stuff to do like implementing the settings for it into the UI, and other stuff.
